if(WIN32)
	if(NOT GLEW_FOUND)
		set(GLEW_DIR "GLEW_DIR-NOTFOUND" CACHE PATH "GLEW binaries directory")
		if(NOT IS_DIRECTORY ${GLEW_DIR})
			message(FATAL_ERROR "Can't find glew")
		elseif(NOT EXISTS ${GLEW_DIR}/lib/Release/x64/glew32.lib)
			message(FATAL_ERROR "glew32.lib is missing")
		else()
			set(GLEW_FOUND TRUE)
			set(GLEW_INCLUDE_DIRS ${GLEW_DIR}/include)
			link_directories(${GLEW_DIR}/lib/Release/x64)
			set(GLEW_LIBRARIES glew32)
			set(GLEW_RUNTIME ${GLEW_DIR}/bin/Release/x64/glew32.dll)
		endif()
	endif()
else()
	find_package(GLEW REQUIRED)
	set(GLEW_LIBRARIES GLEW::glew)
endif()